#include<iostream>
using namespace std;
int main()
{
    int n,right=0,left=0,re=0;
    cin>>n;
    int nx,ny,x=0,y=0;
    int f=1;// x方向 右
    for(int i=0;i<n;i++)
    {
        cin>>nx>>ny;
        if(nx==x)    
        {
            if(ny>y)
            {
                if(f==1)
                {
                    left++;
                }
                if(f==-1)
                {
                    right++;
                }
                if(f==-2)
                {
                    re++;
                }
                f=2;   
            }
            else{
                if(f==1){
                right++;
            }
            if(f==-1)
            {
                left++;
            }
            if(f==2)
            {
                re++;
            }
            f=-2;   
            }
        }
        else
        {
            if(nx>x)
            {
                if(f==2)
                {
                 right++;
                }
                if(f==-1)
                {
                    re++;
                }
                if(f==-2)
                {
                    left++;
                }
                f=1;  
            }
            else 
            {
            if(f==1){
                re++;
            }
            if(f==2)
            {
                left++;
            }
            if(f==-2)
            {
                right++;
            }
            f=-1;   
            }
        }
        x=nx;
        y=ny;
    }
    cout<<left<<" "<<right<<" "<<re<<endl;
}